test-job1:    
  stage: test  
  script:    
    - echo "--------------- METEOR TESTS ---------------"    
    - echo "*** Current Repo ***"    
    - pwd    
    - echo "*** Install Meteor ***"    
    - curl https://install.meteor.com/ | sh    
    - echo "*** Meteor Commands***"    
    - meteor npm install --allow-superuser    
    - meteor test --once --driver-package meteortesting:mocha --allow-superuser